language: python

matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"

  fast_finish: true
dist: xenial
sudo: true

install:
- pip install coverage
- pip install coveralls
- pip install -e .

script:
- coverage run --source=pysyncthru setup.py test

after_success:
- coverage report
- coveralls

