language: python

matrix:
  include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"

  fast_finish: true
  allow_failures:
    - python: "3.7-dev"

install: pip install -U tox

script: tox
